name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build workspaces
        run: |
          npm -w @pwn-mcp/core run build
          npm -w @pwn-mcp/config run build
          npm -w @pwn-mcp/storage run build
          npm -w @pwn-mcp/orchestrator run build
          npm -w @pwn-mcp/adapters run build
          npm -w @pwn-mcp/templates run build
          npm -w @pwn-mcp/mcp-server run build

      - name: Smoke test
        run: npm -w @pwn-mcp/mcp-server run smoke