name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: |
          npm -w @pwn-mcp/core run build
          npm -w @pwn-mcp/config run build
          npm -w @pwn-mcp/storage run build
          npm -w @pwn-mcp/orchestrator run build
          npm -w @pwn-mcp/adapters run build
          npm -w @pwn-mcp/templates run build
          npm -w @pwn-mcp/mcp-server run build

      - name: Run smoke
        run: npm -w @pwn-mcp/mcp-server run smoke

      - name: Create tarball
        run: |
          VERSION="${{ inputs.version || github.ref_name }}"
          tar -czf "pwn-mcp-${VERSION}.tar.gz" \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=.github \
            --exclude='*.log' \
            .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version || github.ref_name }}
          name: ${{ inputs.version || github.ref_name }}
          files: pwn-mcp-${{ inputs.version || github.ref_name }}.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
